# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a095384c99cc6aed80aeb3cd06b28c54b581ca26c8478f67df47aa7fcdb5d6933c333408566ce5654dc22295fbccb83293c5973ee3064e7c2573452f1dce343c

test:
  secret_key_base: 12fc4e08a3c3b452251be233108386ffd37948a2f607da175971cc169a1b5404442a4ac7b2867fdaa0668babf87ca39a667322f2db51c6e0c8bacd11db32690e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
